### ISSUE TITLE
When autocompleting an at-room notif, the avatar is cut in half

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11461]
![](https://i.imgur.com/Bytjzc6.png)

**Comment by turt2live** [comment]
this was in the composer btw (CIDER)

**Comment by t3chguy** [comment]
This also affects User Pills
![image](https://user-images.githubusercontent.com/2403652/69420195-1d493500-0d16-11ea-92b6-fc090ae0427f.png)
and other room Pills
![image](https://user-images.githubusercontent.com/2403652/69420206-22a67f80-0d16-11ea-8af4-a9f666a45ebb.png)


```css
.mx_BasicMessageComposer .mx_BasicMessageComposer_input span.mx_UserPill::before, .mx_BasicMessageComposer .mx_BasicMessageComposer_input span.mx_RoomPill::before {
    background-size: 24px;
    background-position-y: center;
    background-position-x: center;
}
```
