### ISSUE TITLE
Memory leaks and client freezes due to mis-interpreted preview

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18314]
I'm not able to extract much information, but devs could be able to interpret this.

#### Description

After refreshing my element client, it froze, after restarting a few times, and finally hitting debugger pause in the Source tab of devtools, i got some more information;

![image](https://user-images.githubusercontent.com/22740616/127746150-30b2cf39-c417-47c4-ad93-ce7fb4d9579d.png)

![image](https://user-images.githubusercontent.com/22740616/127746216-d3c7ff1b-22c8-443f-8eac-3ee394f9f3c9.png)

Here's the copy of that string (inside the `Output`);

```
Hi, i am having issues with signal bridge. I am not able to send or receive messages. I tried to find the log file but couldn't find it.
logging:
    version: 1
    formatters:
        colored:
            (): mautrix_signal.util.ColorFormatter
            format: '[%(asctime)s] [%(levelname)s@%(name)s]
```

Here's the string as seen in `mapping`;

```
Hi, i am having issues with signal bridge. I am not able to send or receive messages. I tried to find the log file but couldn't find it.
logging:
    version: 1
    formatters:
        colored:
            (): mautrix_signal.util.ColorFormatter
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
        normal:
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: normal
            filename: ./mautrix-signal.log
            maxBytes: 10485760
            backupCount: 10
        console:
            class: logging.StreamHandler
            formatter: colored
    loggers:
        mau:
            level: DEBUG
        aiohttp:
            level: INFO
    root:
        level: DEBUG
        handlers: [file, console]

This is how the log config looks like but I don't see mautrix-singal.log in the directory where signal bridge is setup. Any suggestions?
```

Here's the stacktrace;

<details>
<summary>Stacktrace</summary>

```
b (languageHandler.tsx:formatted:2)
Object.assign.interpolate (languageHandler.tsx:formatted:2)
_ (languageHandler.tsx:formatted:2)
getTextFor (languageHandler.tsx:formatted:2)
generatePreview (languageHandler.tsx:formatted:2)
await in generatePreview (async)
getPreviewForRoom (languageHandler.tsx:formatted:2)
generatePreview (languageHandler.tsx:formatted:2)
o (languageHandler.tsx:formatted:2)
gi (languageHandler.tsx:formatted:2)
Ba (languageHandler.tsx:formatted:2)
Gs (languageHandler.tsx:formatted:2)
wc (languageHandler.tsx:formatted:2)
Ec (languageHandler.tsx:formatted:2)
yc (languageHandler.tsx:formatted:2)
hc (languageHandler.tsx:formatted:2)
(anonymous) (languageHandler.tsx:formatted:2)
t.unstable_runWithPriority (languageHandler.tsx:formatted:2)
Vr (languageHandler.tsx:formatted:2)
zr (languageHandler.tsx:formatted:2)
Hr (languageHandler.tsx:formatted:2)
sc (languageHandler.tsx:formatted:2)
enqueueSetState (languageHandler.tsx:formatted:2)
f.setState (languageHandler.tsx:formatted:2)
(anonymous) (languageHandler.tsx:formatted:2)
s.emit (languageHandler.tsx:formatted:2)
(anonymous) (languageHandler.tsx:formatted:2)
trigger (languageHandler.tsx:formatted:2)
makeReady (languageHandler.tsx:formatted:2)
await in makeReady (async)
onReady (languageHandler.tsx:formatted:2)
onReady (languageHandler.tsx:formatted:2)
(anonymous) (languageHandler.tsx:formatted:2)
e._invokeCallback (languageHandler.tsx:formatted:2)
e.dispatch (languageHandler.tsx:formatted:2)
dispatch (languageHandler.tsx:formatted:2)
o (languageHandler.tsx:formatted:2)
s.emit (languageHandler.tsx:formatted:2)
updateSyncState (languageHandler.tsx:formatted:2)
_sync (languageHandler.tsx:formatted:2)
await in _sync (async)
s (languageHandler.tsx:formatted:2)
await in s (async)
a (languageHandler.tsx:formatted:2)
```

</details>

Update: The culprit was a message in `#signal:maunium.net`, i fixed this by bumping the message with my own, making sure it doesnt appear in the sidebar again.

#### Version information

This happened on `develop.`, `staging.` and my desktop app;

- **Platform**: desktop

- **OS**: Windows
- **Version**: ~~Unable, but latest.~~ 1.7.33, after regaining access.
