### ISSUE TITLE
Right margin on messages too big

### ISSUE THREAD

**Issue by andrewshadura** [vector-im/element-web#18354]
The right margin for messages set to an absolute value of 110 px is too big for small-sized screens. The issue appeared after one of the last updates.

```css
.mx_RoomView_timeline_rr_enabled
.mx_EventTile:not([data-layout="bubble"])
.mx_EventTile_line {
    margin-right: 110px;
}
```
![image](https://user-images.githubusercontent.com/309253/127965946-981740e7-8609-48e5-b395-115327ad0258.png)

![image](https://user-images.githubusercontent.com/309253/127966032-fe7f6c68-62a6-4810-af75-21153ac32da4.png)
