### ISSUE TITLE
Newlines in multi-line strings in Python code blocks format weirdly; string jumps on top of line

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-web#18739]
### Steps to reproduce

1. Send a Python code block in Element Web. (remove the backslashes from below)

```
\```python
	  x = """a
b"""
\```
```

2. Look at message, see below.

N.B. think the source of this issue is this CSS rule (poked at with dev tools, sorry):

```css
.mx_EventTile_content .markdown-body pre code > * {
    display: inline-block;
}
```

### What happened?

The multiline string sits on top of the line, confusingly.

<img width="249" alt="image" src="https://user-images.githubusercontent.com/38398653/130793436-6a181d0b-2484-4392-9e10-4ef86b641bd3.png">

### What did you expect?

Changing to this (though there might be side effects, sorry I haven't checked):
```css
.mx_EventTile_content .markdown-body pre code > * {
    display: inline;
}
```

Gives:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/38398653/130793522-3b17b0f1-3147-492c-968f-5090f754631d.png">

### Operating system

Linux KDE Neon 20.04

### Browser information

Firefox 90.0.2

### URL for webapp

https://develop.element.io

### Have you submitted a rageshake?

No
