### ISSUE TITLE
Allow to change $focus-bg-color (#343a46) in a custom theme

### ISSUE THREAD

**Issue by Oha-you** [vector-im/element-web#20018]
#### What would you like to do?

Be able to change `$focus-bg-color` (also known as `$room-highlight-color` or `#343a46`) when using a custom theme like [Discord Dark](https://github.com/aaronraimist/element-themes#discord-dark-theme), similarly to the other variables mentioned in https://github.com/vector-im/element-web/issues/19381#issuecomment-942268168

#### Why would you like to do it?

Since this value is hardcoded in a compiled version of Element v1.9.5, some UI elements are hardly visible:
1. User/room pills (not highlighted ones). Existing issue: #12629
![2021-12-02_174147](https://user-images.githubusercontent.com/82098328/144459082-93ec6d8f-0e0b-4ef4-abb0-3439f7baa708.png)
CSS code (`theme-dark-custom.css`):
    ```css
    .mx_EventTile_content .markdown-body a.mx_UserPill, .mx_UserPill {
        color: var(--timeline-text-color);
        background-color: #343a46;
    }

    .mx_EventTile_content .markdown-body a.mx_GroupPill, .mx_EventTile_content .markdown-body a.mx_RoomPill, .mx_GroupPill, 
    .mx_RoomPill {
        color: #fff;
        background-color: #343a46;
    }
    ```
2. Hovered items of context menus:
![2021-12-02_174301](https://user-images.githubusercontent.com/82098328/144460049-e4364112-af10-4b3e-b1c6-574d56cb248c.png)
    ```css
    .mx_IconizedContextMenu .mx_IconizedContextMenu_optionList .mx_AccessibleButton:hover {
        background-color: #343a46;
    }
    ```
3. Switcher backgrounds in settings:
![2021-12-02_174348](https://user-images.githubusercontent.com/82098328/144460476-b2324fc3-c27c-4fa6-b82c-af2a385d0ccd.png)
    ```css
    .mx_ToggleSwitch {
        ...
        background-color: #343a46;
    }
    ```

#### How would you like to achieve it?
Hopefully this can be done as a part of color variables overhaul that can be seen in recent Element releases.
