### ISSUE TITLE
Increase space sidebar icon size from 32px to 40px

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20089]
#### What would you like to do?

Increase the size of space icons in the sidebar.

#### Why would you like to do it?

Compared to some other messengers in likewise window sizes and depths, the space icons are actually rather hard to see, i'd like for them to be a bit bigger.

### Additional context

Here is a comparison image on a 2560 x 1440 monitor (slightly cropped on bottom and top for system status bars);

Without size increase;

![image](https://user-images.githubusercontent.com/22740616/145080400-8f38c81b-207c-4369-9924-2a03e62a2cb8.png)

With size increase;

![image](https://user-images.githubusercontent.com/22740616/145080461-b405e9fa-27e2-44a1-832b-4ea5b4424973.png)

---

Programmer note, and cc @SimonBrandner, i had to add the following CSS;

```css
.mx_SpacePanel .mx_SpaceButton .mx_BaseAvatar_image {
    width: 40px !important;
    height: 40px !important;
}
```
Because every space icon defines their height and width in their own `style` attribute, i think that could be easily cleaned up.
