### ISSUE TITLE
Failed to authenticate with ma1sd Identity Server, but ma1sd logs tell me successfull to authenticate

### ISSUE THREAD

**Issue by n4rkip0d** [vector-im/element-web#20155]
### Steps to reproduce

I have a working Matrix / Element chat server.

I want to use the password_provider: `rest_auth_provider.RestAuthProvider` instead of the `ldap_auth_provider.LdapAuthProvider`.
It will be working with ma1sd service.

#### What did you expect?

Login with the Active Directory Credentials then use the Element chat.

#### What happened instead?

Failed to authenticate.

Here's the screenshot showing successful login with ma1sd and not successful from the Element web:

![matrix labo failed](https://user-images.githubusercontent.com/68989865/145791929-a0c34511-6354-4017-a347-515cecc59468.PNG)

1. Matrix config file:

```
modules:
pid_file: "/var/run/matrix-synapse.pid"
public_baseurl: https://matrix-labo.company.lan/
presence:

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
		
manhole_settings:
limit_usage_by_mau: false
mau_stats_only: false
limit_remote_rooms:
templates:
retention:

caches:
  per_cache_factors:
  
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: synapse_test_user
    password: password
    database: synapse_db_test
    host: 192.168.1.10
    port: 5432
    cp_min: 5
    cp_max: 10
	
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: "/var/lib/matrix-synapse/media"
max_upload_size: 50M
url_preview_accept_language:
oembed:
enable_registration: false
registration_shared_secret: secret_pass
enable_set_displayname: false
metrics_flags:
room_prejoin_state:
macaroon_secret_key: secret_pass2

signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
old_signing_keys:

trusted_key_servers:
  - server_name: "matrix.org"
  
saml2_config:
  sp_config:
  user_mapping_provider:
    config:
oidc_providers:
cas_config:
sso:
password_config:
   policy:
ui_auth:
email:
push:
user_directory:
    search_all_users: true
stats:
opentracing:
redis:

password_providers:
  - module: "rest_auth_provider.RestAuthProvider"
    config:
      endpoint: "http://192.168.1.20:8090"

```

2. Mas1d config file

```
matrix:
  domain: 'matrix-labo.company.lan'
  v1: false
  v2: true

enable_registration: false
key:
  path: '/var/lib/ma1sd/keys'

storage:
  provider:
    sqlite:
      database: '/var/lib/ma1sd/store.db'

ldap:
  enabled: true
  lookup: true 
  activeDirectory: true
  defaultDomain: 'company.lan'
  connection:
    host: 'ad-01.company.lan'
    port: 389
    bindDn: 'cn=admin.user,ou=Users,dc=company,dc=lan'
    bindPassword: 'password'
    baseDNs:
      - 'ou=Users,dc=company,dc=lan'
  attribute:
    uid:
      type: 'uid'
      value: 'sAMAccountName'
    name: 'cn'

hashing:
  enabled: true 
  pepperLength: 20 
  rotationPolicy: per_requests
  hashStorageType: sql
  algorithms:
    - sha256 
  requests: 10 

logging:
  root: error     
  app: info     
  requests: false 
```

3. Element config file

```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix-labo.company.lan",
            "server_name": "matrix-labo.company.lan"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
    "disable_custom_urls": true,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": true,
    "brand": "Element Labo",
    "integrations_ui_url": "",
    "integrations_rest_url": "",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "bug_report_endpoint_url": "https://element.io/bugreports/submit",
    "defaultCountryCode": "GB",
    "showLabsSettings": false,
    "features": { },
    "default_federate": true,
    "default_theme": "light",
    "roomDirectory": {
        "servers": [
            "matrix.org"
        ]
    },
    "piwik": {
        "url": "https://piwik.riot.im/",
        "whitelistedHSUrls": ["https://matrix.org"],
        "whitelistedISUrls": ["https://vector.im", "https://matrix.org"],
        "siteId": 1
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    },
    "settingDefaults": {
        "breadcrumbs": true
    },
    "jitsi": {
        "preferredDomain": "jitsi.riot.im"
    }
}

```

4. Nginx config file (Matrix / Mas1d)

```
server {
    listen 80;
    server_name matrix-labo.company.lan;
    return 301 https://matrix-labo.company.lan$request_uri;
}

server {
    listen 443 ssl;
    server_name matrix-labo.company.lan;

    ssl_certificate /etc/ssl/certs/matrix-labo.pem;
    ssl_certificate_key /etc/ssl/certs/matrix-labo-privkey.pem;

    location /_matrix/client/r0/login {
        proxy_pass http://localhost:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

#    location /_matrix/client/r0/user_directory {
 #       proxy_pass http://localhost:8090/_matrix/client/r0/user_directory;
  #      proxy_set_header Host $host;
   #     proxy_set_header X-Forwarded-For $remote_addr;
   # }

    location /_matrix/identity {
        proxy_pass http://localhost:8090/_matrix/identity;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }


    location ~* ^(\/_matrix|\/_synapse\/client) { 
#    location \_matrix { 

        proxy_pass http://localhost:8008;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        #proxy_set_header X-Forwarded-Proto $scheme;
        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
        client_max_body_size 10M;

    }
   
}

server {
    listen 8448 ssl;
    server_name matrix-labo.company.lan;

    ssl_certificate /etc/ssl/certs/matrix-labo.pem;
    ssl_certificate_key /etc/ssl/certs/matrix-labo-privkey.pem;

    location / {
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr;

    }
}
```

5. Nginx config file (Element)

```
server {
    listen 80;
    server_name element-labo.company.lan;
    return 301 https://element-labo.company.lan$request_uri;
}


server {
    listen 443 ssl;
    server_name element-labo.company.lan;
    root /var/www/element/;
    index index.html index.php index.htm;

    ssl_certificate /etc/ssl/certs/element-labo.pem;
    ssl_certificate_key /etc/ssl/certs/element-labo-pvkey.pem;
    #ssl_dhparam /etc/ssl/certs/dhparam-chat.pem;

    access_log /var/log/nginx/element-labo.company.lan.access.log;
    error_log /var/log/nginx/element-labo.company.lan.error.log;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000";
#    add_header Content-Security-Policy "frame-ancestors 'none'";

    ssl_ciphers "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA";
    ssl_session_cache shared:SSL:20m;
    ssl_session_timeout 15m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ecdh_curve X25519:P-521:P-384:P-256;
    ssl_prefer_server_ciphers on;


    location / {
                try_files $uri $uri/ =404;
        }

}
```

If anyone have an idea ? T

Thank you in advance.

### Operating system

Windows 10 v19043.1387

### Browser information

Google Chrome v96.0.4664.93

### URL for webapp

https://chat.company.lan

### Application version

Element version v1.9.6

### Homeserver

https://matrix.company.lan

### Will you send logs?

No

**Comment by t3chguy** [comment]
Can you use your browser's network devtools tab to show the response coming from Synapse to the /login request?

This definitely seems like a backend issue rather than an Element Web one but this will help point you in the right direction.

**Comment by n4rkip0d** [comment]
I did then a `strace` command to follow the issue that may not appear in the default log file:



```
strace -f -s 200 -p PID
```

When I try to login:

```
[pid  8168] write(7, "2021-12-13 11:42:22,991 - synapse.rest.client.login - 267 - INFO - POST-18 - Got login request with identifier: {'type': 'm.id.user', 'user': 'user user'}, medium: None, address: None, user: None\n", 200) = 200
[pid  8168] write(7, "2021-12-13 11:42:22,991 - rest_auth_provider - 46 - INFO - POST-18 - Got password check for @user user:matrix-labo.company.lan\n", 133) = 133
[pid  8168] write(7, "2021-12-13 11:42:23,009 - rest_auth_provider - 58 - INFO - POST-18 - User not authenticated\n", 92) = 92
[pid  8168] write(7, "2021-12-13 11:42:23,013 - synapse.handlers.auth - 967 - WARNING - POST-18 - Attempted to login as @user user:matrix-labo.company.lan but they do not exist\n", 161) = 161
[pid  8168] getpid()                    = 8168
```

I found out that it was trying to connect with the Common Name instead of the sAMAccountName.


**I change the ma1sd config file and change the name: value**

```
attribute:
    uid:
      type: 'uid'
      value: 'sAMAccountName'
      #name: 'cn'
      name: 'sAMAccountName'
```

Then the log strace show me now it try to log with the sAMAccountName:


```
[pid 10211] write(7, "2021-12-13 12:04:02,236 - synapse.rest.client.login - 267 - INFO - POST-16 - Got login request with identifier: {'type': 'm.id.user', 'user': 'user'}, medium: None, address: None, user: None\n", 194) = 194
[pid 10211] write(7, "2021-12-13 12:04:02,236 - rest_auth_provider - 46 - INFO - POST-16 - Got password check for @user:matrix-labo.company.lan\n", 127) = 127
[pid 10211] write(7, "2021-12-13 12:04:02,254 - rest_auth_provider - 62 - INFO - POST-16 - User @user:matrix-labo.company.lan authenticated\n", 123) = 123
[pid 10211] write(7, "2021-12-13 12:04:02,257 - rest_auth_provider - 76 - INFO - POST-16 - User @user:matrix-labo.company.lan already exists, registration skipped\n", 146) = 146
[pid 10211] write(7, "2021-12-13 12:04:02,257 - rest_auth_provider - 79 - INFO - POST-16 - Handling profile data\n", 91) = 91
[pid 10211] write(7, "2021-12-13 12:04:02,258 - synapse.handlers.auth - 2074 - WARNING - POST-16 - Failed to run module API callback <function load_single_legacy_password_auth_provider.<locals>.async_wrapper.<locals>.wrapp"..., 279) = 279
```

But now it gives me a API Module error.
