### ISSUE TITLE
Can not log onto private browser or the Destop app (connected via Chrome web version since 7 month)

### ISSUE THREAD

**Issue by s0p4LiN** [vector-im/element-web#22732]
### Steps to reproduce

1. Where are you starting? What can you see?

All users having a new workstation, and so on, need to connect again and load all history can not connect through Element anymore.

3. What do you click?

Access to the Element web URL from the company network

5. More steps…

Happens from a private tab to act as a new user or try to connect on the Desktop app

![image](https://user-images.githubusercontent.com/68989865/177216340-8b6f3c1f-5713-431b-96f0-13b91c012f95.png)

#### What did you expect?

Connect on the session chat

#### What happened instead?

Loop syncing, matrix element has 64Gb RAM and 12 vcpu, 1Gbps network card. Load at 0.48.
Postgresql server for matrix has 16Gb RAM and 8 vcpu, 1 Gbps network card. Load at 5.

The synchronisation is running since 12 hours, 5 employees are blocked.

What do I need to do ?

### Operating system

Windows 10

### Browser information

Google Chrome 103.0.5060.114

### URL for webapp

https://chat.company.lan

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### Homeserver

1.59.1

### Will you send logs?

No

**Comment by s0p4LiN** [comment]
I have just updated to Synapse 1.61.1 and Element 1.10.15, still same issue.

**Comment by s0p4LiN** [comment]
Here's my configuration files:

- Matrix:

```
modules:
pid_file: "/var/run/matrix-synapse.pid"
public_baseurl: https://matrix.company.lan/
presence:

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false

manhole_settings:
limit_usage_by_mau: false
limit_remote_rooms:
templates:

retention:
  enabled: false

caches:
  per_cache_factors:

database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: synapse_user
    password: secret_password
    database: synapse_db
    host: 192.168.1.10
    port: 5432
    cp_min: 5
    cp_max: 10
    keepalives_idle: 10
    keepalives_interval: 10
    keepalives_count: 3

log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: "/element-data/media"
max_upload_size: 15M
url_preview_accept_language:
oembed:
turn_uris: [ "turn:coturn.company.lan:5349?transport=udp", "turn:coturn.company.lan:5349?transport=tcp" ]
turn_shared_secret: "secret_turn"
enable_registration: false
registration_shared_secret: reg_secret
account_threepid_delegates:
enable_set_displayname: false
metrics_flags:
room_prejoin_state:
macaroon_secret_key: secret_macaroon
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
old_signing_keys:
  
trusted_key_servers:
  - server_name: "matrix.org"
saml2_config:
  sp_config:
  user_mapping_provider:
    config:
oidc_providers:
cas_config:
sso:
password_config:
   policy:
ui_auth:
email:
push:
user_directory:
    search_all_users: true
stats:
opentracing:
redis:

password_providers:
  - module: "rest_auth_provider.RestAuthProvider"
    config:
      endpoint: "http://192.168.1.20:8090"
```

- Element:

```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.company.lan",
            "server_name": "matrix.company.lan"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
    "permalink_prefix": "https://chat.company.lan",
    "disable_custom_urls": true,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": true,
    "brand": "SuperChat",
    "integrations_ui_url": "https://dimension.company.lan/element",
    "integrations_rest_url": "https://dimension.company.lan/api/v1/scalar",
    "integrations_widgets_urls": ["https://dimension.company.lan/widgets"],
    "integrations_jitsi_widget_url": "https://dimension.company.lan/widgets/jitsi",
    "bug_report_endpoint_url": "https://element.io/bugreports/submit",
    "uisi_autorageshake_app": "element-auto-uisi",
    "default_country_code": "FR",
    "show_labs_settings": false,
    "features": {
    "feature_pinning": true,
    "feature_presence_in_room_list": true,
    "feature_custom_status": true,
    "feature_dnd": true,
    "feature_message_right_click_context_menu": true,
    "feature_roomlist_preview_reactions_all": true,
    "feature_breadcrumbs_v2": true
    },
    "default_federate": true,
    "default_theme": "dark",
    "room_directory": {
        "servers": [
            "matrix.company.lan"
        ]
    },
    "branding": {
    "welcome_background_url": "https://chat.company.lan/themes/element/img/backgrounds/company-wallpaper.jpg",
    "auth_header_logo_url": "https://chat.company.lan/themes/element/img/backgrounds/company-logo.png",
    "auth_footer_links": [{"text": "company", "url": "https://www.company.net/fr/"},{"text": "[EN] How to use it", "url": "link"},{"text": "[FR] Guide d'utilisation", "url": "link"}]
    },
    "piwik": {
        "url": "https://piwik.riot.im/",
        "whitelisted_hs_urls": ["https://matrix.company.lan", "chat.company.lan"],
        "whitelisted_is_urls": ["https://vector.im", "https://matrix.company.lan", "chat.company.lan"],
        "site_id": 1
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    },
    "setting_defaults": {
        "breadcrumbs": true
    },
    "jitsi": {
        "preferred_domain": "meet.company.lan",
        "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
    }
}
```
