### ISSUE TITLE
Flaky test at the SonarCloud step due to "no artifacts found"

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25334]
Sometimes, when we try to kick off the SonarCloud step, the artifacts from the previous workflow are not yet present, and it fails.

Examples of failures caused by this:

* https://github.com/matrix-org/matrix-js-sdk/actions/runs/4993311321
* https://github.com/matrix-org/matrix-js-sdk/actions/runs/4993512503

**Comment by andybalaam** [comment]
The failing job is [.github/workflows/sonarqube.yml](https://github.com/matrix-org/matrix-react-sdk/blob/82e32035fdf95ae03e5092c6147be0892c05edab/.github/workflows/sonarqube.yml), which is kicked when Tests finishes:

```
on:
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed
```
