### ISSUE TITLE
Multiple uploads resulting in CANCELED

### ISSUE THREAD

**Issue by Cyberes** [vector-im/element-web#25756]
### Steps to reproduce

I am attempting to upload two video files (each about 30 MB) to a room at the same time. This always fails with a generic error message popup (The file '[filename]' failed to upload.). There is no error in the console and the network of the debug window shows the fetch request as (canceled). Synapse logs don't show any errors and neither does Openresty. Uploading the files one at a time works, but uploading them together always fails.

We've investigated the Synapse side of things and everything seems to be working -> https://github.com/matrix-org/synapse/issues/15841

- My upload limit in Synapse and Openresty (reverse proxy) is 40M. This has been an issue for a while and I have not discovered the root cause yet.
- My client is desktop and web Element on Ubuntu.
- I have a media worker with an S3 storage provider setup (see config below).

```yaml
media_store_path:                                 "/mnt/matrix-storage/media"

media_storage_providers:
- module:                                         s3_storage_provider.S3StorageProviderBackend
  store_local:                                    True
  store_remote:                                   True
  store_synchronous:                              True
  config:
      bucket:                                     matrix-synapse
      endpoint_url:                               'https://xxx.r2.cloudflarestorage.com/matrix-synapse'
      access_key_id:                              'xxx'
      secret_access_key:                          'xxx'
```

#### What did you expect?
Files are uploaded.

#### What happened instead?
Element said the upload failed and the request in the network console showed `(CANCELED)`.

### Operating system

Ubuntu

### Application version

1.11.34

### How did you install the app?

Repository

### Homeserver

matrix.evulid.cc

### Will you send logs?

Yes, but I didn't find any relevant logs during my investigation.
