### ISSUE TITLE
Unread room indicator for collapsed roomlist

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#5454]
When the left sidebar is collapsed, you can't tell which rooms have unread messages

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/4369

**Comment by uhoreg** [comment]
Something like:

```css
.mx_LeftPanel.collapsed .mx_RoomTile_unread .mx_RoomTile_avatar_container::after {
    border: solid 3px blue;
    border-radius: 3px;
    display: block;
    position: absolute;
    top: 0px;
    content: "";
    height: 0;
    width: 0;
    right: 0;
}
```

would give

![image](https://user-images.githubusercontent.com/1012976/33399689-853d9cca-d521-11e7-9512-24e55b9e55ce.png)

(with the middle three rooms being unread, and the outer two rooms being read).  A different colour would probably be better.
